# fly.toml app configuration file generated for awe-game-server on 2024-12-25T14:30:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'awe-game-server'
primary_region = 'iad'

[build]

[env]
FLY_PROXY = 'awe-game-router.fly.dev'
SINGLE_ROOM = 'true'
ROOM_IDLE_TIMEOUT_SEC = '1800'

[http_service]
internal_port = 2567
force_https = true
auto_stop_machines = 'off'
auto_start_machines = false
min_machines_running = 0
processes = ['app']

[[restart]]
policy = "never"


[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 2
